spring:
  batch:
    job:
      enabled: false          # 앱 시작 시 자동 실행 방지 (스케줄러가 담당)
    jdbc:
      initialize-schema: always  # Batch 메타 테이블 자동 생성
  datasource:
    url: jdbc:mysql://localhost:3306/mutrent?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Pongchul1!
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버로 변경
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  # MySQL Dialect로 변경
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          fetch_size: 100

crawler:
  base-url: http://localhost:8000  # Python FastAPI 서버 주소
#logging:
#  level:
#    root: DEBUG
